# postgres-service.yaml
# 作用：為 PostgreSQL 提供穩定的網路端點
# 其他應用可以透過這個 Service 來訪問 PostgreSQL

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
  labels:
    app: postgres
    project: k8s-fullstack
spec:
  # 選擇器：選擇標籤為 app: postgres 的 Pod
  selector:
    app: postgres
  
  # 端口配置
  ports:
  - name: postgres
    port: 5432        # Service 暴露的端口
    targetPort: 5432  # Pod 中容器的端口
    protocol: TCP
  
  # 服務類型
  type: ClusterIP     # 只在集群內部可訪問
  
  # 如果需要外部訪問（測試用），可以改為：
  # type: NodePort
  # 然後會自動分配一個外部端口
