# 域名 Secret 配置範例
# 複製為 domain-secret.yaml 並填入實際域名
# 
# 使用方式：
# 1. cp domain-secret.example.yaml domain-secret.yaml
# 2. 編輯 domain-secret.yaml，替換所有域名
# 3. kubectl apply -f domain-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: domain-config
  namespace: fullstack-app
  labels:
    app: ingress
    component: domain-config
type: Opaque
stringData:
  # 主域名配置
  PRIMARY_DOMAIN: "your-domain.com"
  
  # 服務完整域名
  N8N_DOMAIN: "n8n.your-domain.com"
  APP_DOMAIN: "app.your-domain.com"
  API_DOMAIN: "api.your-domain.com"
  
  # CORS 允許的源 (JSON 格式)
  CORS_ORIGINS: |
    [
      "https://app.your-domain.com",
      "https://n8n.your-domain.com"
    ]
  
  # SSL/TLS 配置
  TLS_SECRET_NAME: "tls-secret"
  CERT_ISSUER: "letsencrypt-prod"
  
  # 路由配置
  GEMMA_API_PREFIX: "/gemma/api"
  STOCK_API_PREFIX: "/stock/api"
  USER_API_PREFIX: "/user/api"
  
  # 安全配置
  SECURITY_HEADERS_ENABLED: "true"
  HSTS_MAX_AGE: "31536000"
