# n8n 內部服務配置
# 提供集群內部的穩定網路端點

apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: fullstack-app
  labels:
    app: n8n
    service: n8n
spec:
  selector:
    app: n8n  # 選擇標籤為 app: n8n 的 Pod
  
  ports:
  - name: http
    port: 80          # Service 暴露的 port
    targetPort: 5678  # Pod 中 n8n 的 port
    protocol: TCP
  
  type: ClusterIP     # 集群內部訪問
