# k8s/n8n/n8n-secret.yaml
# 複製 database Secret 到 fullstack-app namespace

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-copy
  namespace: fullstack-app
  labels:
    app: n8n
    copied-from: database-namespace
type: Opaque
data:
  # 這些值需要與 database namespace 中的 postgres-secret 保持一致
  # TODO: 替換為實際的 base64 編碼值
  n8n-user: bjhuX3VzZXI=         # echo -n "n8n_user" | base64
  n8n-password: eW91ci1uOG4tcGFzc3dvcmQ=    # 替換為你的實際密碼