# Ollama PVC - 持久化存儲配置
# 功能：為 Ollama 創建 8GB 的存儲空間，用來儲存 Gemma 2B 模型和緩存

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: ai-services
  labels:
    app: ollama
    component: storage
spec:
  # 存取模式：只能被一個 Pod 掛載（LLM 模型不需要共享）
  accessModes:
    - ReadWriteOnce
  
  # 儲存空間：8GB（Gemma 2B 約 3GB + 5GB 緩存空間）
  resources:
    requests:
      storage: 8Gi
  
  # 使用 Rancher Desktop 的預設存儲類別
  storageClassName: local-path