# Gemma Backend API 配置
# 集中管理環境變數和配置參數

apiVersion: v1
kind: ConfigMap
metadata:
  name: gemma-backend-config
  namespace: fullstack-app
  labels:
    app: gemma-backend
    component: config
data:
  # Ollama 服務配置
  OLLAMA_URL: "http://ollama-service.ai-services.svc.cluster.local:11434"
  MODEL_NAME: "gemma2:2b"
  REQUEST_TIMEOUT: "60"
  
  # API 服務配置
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  
  # CORS 配置
  ALLOWED_ORIGINS: "*"
  
  # AI 模型參數
  DEFAULT_TEMPERATURE: "0.3"
  DEFAULT_TOP_P: "0.9"
  MAX_TOKENS: "1000"
  
  # 服務配置
  API_ROOT_PATH: "/gemma/api"
  
  # 效能配置
  WORKERS: "1"
  KEEPALIVE: "65"
